name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-issue-message: |
            Hey, there! 👋
            This issue has been marked as **stale** and will be closed soon.
            Feel free to reopen it if you still need help 👍

          stale-pr-message: |
            Hey, there! 👋
            This PR has been marked as **stale** and will be closed soon.
            Feel free to reopen it if needed 👍

          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"

          days-before-stale: 30
          days-before-close: 5
